org.gradle.jvmargs=-Xmx5G
org.gradle.parallel=true
org.gradle.caching=true

# https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21
parchment_mappings_version=2024.11.10
minecraft_version=1.21.1
fabric_version=0.114.0+1.21.1
loader_version=0.16.9

mod_id=sophisticatedstorageinmotion
mod_name=Sophisticated Storage In Motion
mod_license=GNU General Public License v3.0
mod_version=0.1.2.1
mod_group_id=sophisticatedstorageinmotion
mod_authors=P3pp3rF1y, Salandora
mod_description=Sophisticated Storage on moving entities.
mod_credits=Created by P3pp3rF1y.
mod_logo_file=SophisticatedStorageInMotionFabric.png
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage-in-motion-unofficial-fabric-port
mod_issue_tracker_url=https://github.com/Salandora/SophisticatedStorageInMotion/issues
mod_sources_url=https://github.com/Salandora/SophisticatedStorageInMotion
github_package_url=https://maven.pkg.github.com/Salandora/SophisticatedStorageInMotion

# Dependencies
sc_version=[1.21.1-1.0.11,1.22)
ss_version=[1.21.1-1.0.10,1.22)

#publish
curseforge_id=1170660
release_type=beta
release_versions=1.21.1
modrinth_project_id=T8h6Gr5g

# adding a module also requires adding a dependency to the FMJ
port_lib_modules = none
port_lib_version = 3.1.0-soph.1

# Compat
# https://modrinth.com/mod/jei/versions?g=1.21.1&l=fabric
jei_version = 19.21.0.246
# https://modrinth.com/mod/rei/versions?g=1.21.1&l=fabric
rei_version = 16.0.783
# architectury_version = 6.0.37
# https://modrinth.com/mod/emi/versions?g=1.21.1&l=fabric
emi_version = 1.1.16+1.21.1

# What recipe viewer to use ('emi', 'rei', or 'jei'. if you change it, don't push it)
recipe_viewer = emi