org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

parchment_minecraft_version=1.21
parchment_mappings_version=2024.11.10
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.80
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=sophisticatedstorageinmotion
mod_name=Sophisticated Storage In Motion
mod_license=GNU General Public License v3.0
mod_version=0.10.5
mod_group_id=sophisticatedstorageinmotion
mod_authors=P3pp3rF1y
mod_description=Sophisticated Storage on moving entities.
mod_credits=Created by P3pp3rF1y.
mod_logo_file=logo.png
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage-in-motion
mod_issue_tracker_url=https://github.com/P3pp3rF1y/SophisticatedStorageInMotion/issues
sonar_project_key=sophisticatedstorageinmotion:SophisticatedStorageInMotion
github_package_url=https://maven.pkg.github.com/P3pp3rF1y/SophisticatedStorageInMotion

jei_mc_version=1.21.1-neoforge
jei_version=19.12.0.131
# first JEI version with Object UID support
jei_version_range=[19.9.0,)
sc_version=[1.21.1-1.2.9,1.22)
ss_version=[1.21.1-1.3.7,1.22)

#publish
curseforge_id=1166930
release_type=release
release_versions=1.21.1
modrinth_project_id=6vtFbyaJ