org.gradle.jvmargs=-Xmx5G
org.gradle.parallel=true
org.gradle.caching=true

# https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03
minecraft_version=1.20.1
fabric_version=0.92.9+1.20.1
loader_version=0.19.2

mod_id=sophisticatedstorageinmotion
mod_name=Sophisticated Storage In Motion
mod_license=GNU General Public License v3.0
mod_version=0.10.5.100
mod_group_id=sophisticatedstorageinmotion
mod_authors=P3pp3rF1y, Salandora
mod_description=Sophisticated Storage on moving entities.
mod_credits=Created by P3pp3rF1y.
mod_logo_file=SophisticatedStorageInMotionFabric.png
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage-in-motion-unofficial-fabric-port
mod_issue_tracker_url=https://github.com/Salandora/SophisticatedStorageInMotion/issues
mod_sources_url=https://github.com/Salandora/SophisticatedStorageInMotion
github_package_url=https://maven.pkg.github.com/Salandora/SophisticatedStorageInMotion

#publish
curseforge_id=1170660
modrinth_project_id=T8h6Gr5g
# Release types: STABLE, BETA, ALPHA
release_type=ALPHA
release_versions=1.20.1

# Dependencies
sc_version=[1.20.1-1.2.7.10,1.20.4)
ss_version=[1.20.1-1.2.6,1.20.4)
sl_version=[1.20.1-0.1.0,1.20.2)

# Compat
# https://modrinth.com/mod/jei/versions?g=1.20.1&l=fabric
jei_version = 15.20.0.105
# https://modrinth.com/mod/rei/versions?g=1.20.1&l=fabric
rei_version = 12.0.684
# architectury_version = 6.0.37
# https://modrinth.com/mod/emi/versions?g=1.20.1&l=fabric
emi_version = 1.1.8+1.20.1

# What recipe viewer to use ('emi', 'rei', or 'jei'. if you change it, don't push it)
recipe_viewer = emi